### PR TITLE
Usgs/earthquake list widget#10

### PR DESCRIPTION
**Pull request by jdbrown-USGS**
fixes usgs/earthquake-list-widget#10

- Changes layout and styles of list widget.
- Fixed overlapping content at smaller sizes
- Fixed roman numerals wrapping at some sizes

### CODE REVIEW

**Comment by ehunter-usgs** [comment]
All
  - `.eqlist > .eqitem`
    - remove background color
    - Update padding, `padding: .75em .25em .75em 2.5em;`
  - `.eqlist > .eqitem > .value`
    - remove height
    - set top and left to zero
  - `.eqlist > .eqitem + .eqitem`
    - update border, `border-top: 1px solid #ddd;`
  - `.eqlist > .eqitem
  - Make sure to update vertical alignment after changing padding
  - What is the order?
  - Make all MMI bubbles the same size, define a width not padding

DYFI List
  - Vertically align MMI bubble

ShakeMap List
  - Vertically align MMI bubble

PAGER List 
  - Vertically align PAGER Bubble 
  - Vertically align MMI bubble with timestamp text (make them the same height, remove padding)

**Comment by jdbrown-USGS** [comment]
- Implemented changes
- The list seems to be out of order this will be addressed in another ticket.

**Comment by ehunter-usgs** [comment]
Consistent left edge
 - Make sure there is padding on the left and right of each list item (around 0.5em).

**Comment by ehunter-usgs** [comment]
merged.

**Pull request closed without merging**
